import Head from "next/head";
import Image from "next/image";
import styles from "mathctx/styles/Home.module.css";
import { useDictionary } from "mathctx/lang/lang";

export default function Home() {
  // get the i18 strings from a nextjs
  // i18n provider
  const d = useDictionary("en");

  return (
    <>
      <Head>
        <title>MathCTX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>{d?.["page.home.title"]}</h1>
      </main>
    </>
  );
}
